#!/bin/bash

env

source /data/configure_spark.sh

IP=$(ip -o -4 addr list eth0 | perl -n -e 'if (m{inet\s([\d\.]+)\/\d+\s}xms) { print $1 }')
echo "MASTER_IP=$IP"

echo "preparing Spark"
prepare_spark $IP /data

echo "starting Hadoop Namenode"
sudo -u hdfs hadoop namenode -format > /dev/null 2>&1
service hadoop-namenode start > /dev/null 2>&1

echo "creating history directory"
sudo -u hdfs hadoop dfsadmin -safemode wait > /dev/null 2>&1
sudo -u hdfs hadoop fs -mkdir hdfs://$IP:9000/user/hdfs/spark-events > /dev/null 2>&1

echo "starting sshd"
/usr/sbin/sshd

sleep 5

echo "starting Spark Master"
cp /root/spark_master_files/run_spark_master.sh /
chmod a+rx /run_spark_master.sh
sudo -u hdfs SPARK_VERSION=$SPARK_VERSION /run_spark_master.sh
